Luna2/Models/AllAnimalViewModel.cs
using Luna2.DataAccess.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Luna2.Models
{
    public class AllAnimalViewModel
    {
        public AllAnimalViewModel(List<AnimalModel> animals,List<PersonModel> persons)
        {
            Animals = animals;
            Persons = persons;
        }
        public List<AnimalModel> Animals { get; }
        public List<PersonModel> Persons {get;}
    }
}

Luna2/Models/AnimalDetailViewModel.cs
using Luna2.DataAccess.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Luna2.Models
{
    public class AnimalDetailViewModel
    {
        public AnimalDetailViewModel(AnimalModel animal, PersonModel person)
        {
            Animal = animal;
            Person = person;
        }
        public AnimalModel Animal { get; }
        public PersonModel Person { get; }
    }
}

Luna2/Models/AnimalModel.cs
using Luna2.DataAccess.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Luna2.Models
{
    public class AnimalViewModel
    {
        public AnimalViewModel(List<AnimalModel> animals)
        {
            Animals = animals;
        }
        public List<AnimalModel> Animals { get; }
    }
}

Luna2/Models/ErrorViewModel.cs
using System;

namespace Luna2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Luna2/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Luna2.DataAccess.DataAccess;
using Luna2.DataAccess.Models;
using Luna2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Luna2.Controllers
{
    public class AnimalController : Controller
    {
        private AnimalData animalData;
        private PersonData personData;
        public AnimalController()
        {
            animalData = new AnimalData();
            personData = new PersonData();
        }
        public IActionResult Index()
        {

            return View(new AllAnimalViewModel(animalData.GetAllAnimals(),personData.GetAllPersons()));
        }

        public IActionResult AnimalDetail(int id)
        {
            return View(new AnimalDetailViewModel(animalData.GetAnimalById(id),GetAllPersons().FirstOrDefault()));
        }

        //Possibly open up later via API call
       


        private List<PersonModel> GetAllPersons()
        {
            PersonData data = new PersonData();

            return data.GetAllPersons();
        }
    }
}

Luna2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Luna2.Models;

namespace Luna2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Luna2/Views/Animal/AnimalDetail.cshtml
@model AnimalDetailViewModel
@{
    ViewData["Title"] = $"Animal Detail - {Model.Animal.AnimalName}";
}

<div class="container">
    <h3>Detail view for @Model.Animal.AnimalName</h3>
    <div class="container">
        @Html.LabelFor(model => model.Animal.AnimalName)
        @Html.TextBoxFor(model => model.Animal.AnimalName)
    </div>
</div>

Luna2/Views/Animal/Index.cshtml
@model AllAnimalViewModel

<div class="container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Animal Name</th>
                <th>Date Of Birth</th>
                <th>Person</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var animal in Model.Animals)
            {
                <tr>
                    <td>
                        <a asp-controller="Animal" asp-action="AnimalDetail" asp-route-id="@animal.Id">@animal.AnimalName</a>
                    </td>

                    <td>
                        @(
                            animal.DateOfBirth.ToLocalTime().ToString("MM/dd/yyyy")
                        )
                    </td>
                    <td>
                        @(Model.Persons.Where(p => p.Id == animal.PersonId)
                            .FirstOrDefault().FirstName
                         )
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Luna2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Luna2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Luna2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Luna2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Index">Our Animals</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Luna2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>